### ISSUE TITLE
All floating point values for sfcollector are truncated to integers

### ISSUE THREAD

**Issue by Snickher** [jedimt/hcicollector#19]
It looks like the to_num() method is calling int() first on all numbers passed to it, which will truncate floats without errors to 0. 

From https://docs.python.org/2/library/functions.html#int
If x is floating point, the conversion truncates towards zero.

Need to find another way to collect number values from SF arrays so that they aren't getting truncated into integers.

**Comment by jedimt** [comment]
I have made the requested change to the collector (per your email).
