### ISSUE TITLE
SolidFire Grafana graphs all have 0-100 set for percentage fields. Should be 0-1.

### ISSUE THREAD

**Issue by Snickher** [jedimt/hcicollector#20]
Once all the numbers are pulled and entered using floats instead of integers, all the Grafana graphs for SolidFire metrics are off by a factor of 100. All the graphs that deal with percentages are coded to be between 1-100. The SF API returns numbers between 0 and 1, and in the case of the throttle volume metric at least, can return values over 1 as well to indicate bursting.

Please fix all the Grafana graphs to report percentages correctly.

**Comment by jedimt** [comment]
I have changed the graphs from "percent" to "percentunit" as per your feedback. 
Please have a look and let me know if I missed anything.
