### ISSUE TITLE
Total IOPS field is being mapped from SF "actualIOPS" field which isn't a total

### ISSUE THREAD

**Issue by Snickher** [jedimt/hcicollector#21]
According to the Element OS API Guide, the actualIOPS is the actual IOPS over the last 500ms only, and the writeOps and readOps for the other fields are cumulative since volume creation. These 2 fields aren't compatable and often the Total is way off, since the system is being queried at an interval of more than 60 seconds.

I've been able to use the following to get a "real" total IOPS field:
netapp.solidfire.cluster.$Cluster.accountID.$AccountID.volume.$Volume.*Ops
sumSeries(), perSecond(), alias(Total)

**Comment by jedimt** [comment]
Amended line 729 in the solidfire-volume dashboard with your fix.
