### ISSUE TITLE
Collection of ESXi stats with IP-based HCI

### ISSUE THREAD

**Issue by scaleoutsean** [jedimt/hcicollector#4]
Three weeks ago I failed to get the ESXi dashboard to work in an IP-based HCI cluster but I didn't have enough time for  detailed troubleshooting.

Today I heard the same problem from another person who tried sfcollector with an IP-based HCI cluster and he told me they managed to get the ESXi dash to work once they shut down everything, created DNS A records for vCenter and ESXi, and tried again. 

Maybe a simple fix would be to ensure host resolution inside of the container, or perhaps document this as a requirement (if this cause-effect can be confirmed).

**Comment by jedimt** [comment]
Since Graphite uses the "." to separate objects the IP stuff does break things. I'll document that as a requirement in the user guide when I rev it next. 

You can still make it work, but instead of picking a name (like sfps-vcsa for instance) you will have to modify the dashboards to make the templating point to the IP address.

**Comment by scaleoutsean** [comment]
A UG modification would be enough.

Another workaround (maybe easier for users without Grafana skills) could be to load a custom etc-hosts into the container via YAML. I don't like the idea, it's just bad (in the first case you have to maintain the patch, in the second a custom /etc/hosts - pick your poison), but some folks may prefer that.

**Comment by scaleoutsean** [comment]
Thanks to this commit, I can use IPv4-based vCenter and ESXi.

https://github.com/cblomart/vsphere-graphite/commit/2a71f15356583b149990fef53bb4db275f7c3efc#diff-3baf47c64847a8fb8aaa8cc2e088513b

I haven't figured out how to actually replace the dot with the underscore but this is good enough for me.

![image](https://user-images.githubusercontent.com/16622642/49325483-20d03300-f57e-11e8-9bd7-ec5c14b662d2.png)

A couple of files should be changed to make this seamless. I made this change to vmwcollector/Dockerfile after `git clone`, and manually replaced changed `.go` files (but properties.go is new and it didn't exist in v0.4, it seems), so I managed to barely make this work for me.

```
#RUN curl -L https://github.com/cblomart/vsphere-graphite/releases/download/v0.4/vsphere-graphite_linux_amd64_v0.4.tgz --output /vsphere-graphite_linux_amd64_v0.4.tgz && \
RUN curl -L https://github.com/cblomart/vsphere-graphite/releases/download/v0.7a/vsphere-graphite_linux_amd64.tgz --output /vsphere-graphite_linux_amd64_v0.7a.tgz && \
    tar -zxvf /vsphere-graphite_linux_amd64_v0.7a.tgz    && \
    mv /vsphere-graphite /usr/local/bin/vsphere-graphite && \
    mv /vsphere-graphite.json /etc/vsphere-graphite.json && \
    rm /vsphere-graphite_linux_amd64_v0.7a.tgz
```
