### ISSUE TITLE
Visualizing_NetApp_HCI_Performance.pdf | Two issues

### ISSUE THREAD

**Issue by eddiepullen** [jedimt/hcicollector#7]
Hi,

I have attempted to use this piece of software you have created, really cool idea I must say.
I have found two things in the PDF that breaks the manual install;

1. In the /docker-compose.yml file there is a directory in the build section for the vmwcollector that does not exist: 

This section:

vmwcollector:
    build: ./vsphere-graphite

Should be:

vmwcollector:
    build: ./vmwcollector

2. In the quick and dirty install, you have the following:

apiVersion: 1
datasources:
  - name: $GRAPHITEVOL
    type: graphite
    access: proxy
    orgId: 1
    url: http://$DOCKERIP:8080
    isDefault: true
    version: 1
    editable: true
    basicAuth: false

This is nowhere inside the manual PDF install documentation so once completed there is no datasource
created in grafana.

Cheers

**Comment by jedimt** [comment]
Thanks for the catch eddiepullen. Sorry its taken so long to get back to you, I've been traveling almost a month non-stop. I'll be updating documentation this week to help resolve this.

**Comment by jedimt** [comment]
I've updated the documentation, as well as provided a short demo and pptx deck. Should be good to go now.
